language: node_js
dist: xenial
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 6
    - node_js: node
    - node_js: lts/*
node_js:
  - 6
  - 8
  - 10
  - 12
  - lts/*
  - node
git:
  depth: 5
